insert into public.product (product_id, description, name, available_quantity, price, category_id) values
                                                                                                (nextval('product_seq'), 'Smartfon Apple iPhone 13', 'iPhone 13', 50, 3999.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Samsung Galaxy S21', 'Galaxy S21', 40, 3499.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon OnePlus 9', 'OnePlus 9', 30, 2999.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Google Pixel 6', 'Google Pixel 6', 30, 3499.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Xiaomi Mi 11', 'Xiaomi Mi 11', 25, 3199.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Sony Xperia 1 III', 'Sony Xperia 1 III', 20, 3799.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Huawei P40 Pro', 'Huawei P40 Pro', 15, 2899.99, 1),
                                                                                                (nextval('product_seq'), 'Smartfon Motorola Edge 20', 'Motorola Edge 20', 20, 2699.99, 1),
                                                                                                (nextval('product_seq'), 'Laptop Dell XPS 13', 'XPS 13', 20, 4999.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop MacBook Air', 'MacBook Air', 15, 5499.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop HP Spectre x360', 'Spectre x360', 10, 6499.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop Lenovo ThinkPad X1 Carbon', 'ThinkPad X1 Carbon', 18, 6599.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop Asus ZenBook 14', 'ZenBook 14', 25, 3999.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop Acer Swift 3', 'Swift 3', 30, 3299.99, 51),
                                                                                                (nextval('product_seq'), 'Laptop Microsoft Surface Laptop 4', 'Surface Laptop 4', 20, 5999.99, 51),
                                                                                                (nextval('product_seq'), 'Telewizor Samsung QLED 55"', 'Samsung QLED 55"', 25, 3999.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor LG OLED 65"', 'LG OLED 65"', 10, 5999.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor Sony Bravia 75"', 'Sony Bravia 75"', 5, 7999.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor Panasonic TX-58GX800E', 'Panasonic TX-58GX800E', 12, 4499.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor Philips 55OLED804', 'Philips 55OLED804', 8, 4999.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor Toshiba 50UL3A63DG', 'Toshiba 50UL3A63DG', 15, 2999.99, 101),
                                                                                                (nextval('product_seq'), 'Telewizor Sharp 55BL5EA', 'Sharp 55BL5EA', 20, 3499.99, 101),
                                                                                                (nextval('product_seq'), 'Aparat Canon EOS R5', 'Canon EOS R5', 8, 12999.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Nikon Z6', 'Nikon Z6', 12, 8999.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Sony Alpha a7 III', 'Sony Alpha a7 III', 10, 9999.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Fujifilm X-T4', 'Fujifilm X-T4', 15, 7499.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Olympus OM-D E-M10 Mark IV', 'Olympus OM-D E-M10 Mark IV', 20, 4499.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Panasonic Lumix GH5', 'Panasonic Lumix GH5', 12, 8499.99, 151),
                                                                                                (nextval('product_seq'), 'Aparat Leica Q2', 'Leica Q2', 5, 18999.99, 151),
                                                                                                (nextval('product_seq'), 'Słuchawki Sony WH-1000XM4', 'Sony WH-1000XM4', 35, 1399.99, 201),
                                                                                                (nextval('product_seq'), 'Słuchawki Bose QuietComfort 35 II', 'Bose QuietComfort 35 II', 30, 1499.99, 201),
                                                                                                (nextval('product_seq'), 'Głośnik JBL Flip 5', 'JBL Flip 5', 50, 599.99, 201),
                                                                                                (nextval('product_seq'), 'Głośnik Bose SoundLink Revolve', 'Bose SoundLink Revolve', 20, 999.99, 201),
                                                                                                (nextval('product_seq'), 'Głośnik Apple HomePod', 'Apple HomePod', 15, 1499.99, 201),
                                                                                                (nextval('product_seq'), 'Słuchawki Apple AirPods Pro', 'Apple AirPods Pro', 25, 1199.99, 201),
                                                                                                (nextval('product_seq'), 'Słuchawki Sennheiser Momentum 3', 'Sennheiser Momentum 3', 18, 1699.99, 201),
                                                                                                (nextval('product_seq'), 'Głośnik Sony SRS-XB43', 'Sony SRS-XB43', 22, 899.99, 201),
                                                                                                (nextval('product_seq'), 'Słuchawki Jabra Elite 85h', 'Jabra Elite 85h', 28, 1199.99, 201),
                                                                                                (nextval('product_seq'), 'Słuchawki Beats Studio3', 'Beats Studio3', 32, 1299.99, 201),
                                                                                                (nextval('product_seq'), 'Głośnik Marshall Stanmore II', 'Marshall Stanmore II', 10, 1499.99, 201);